# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 716)
        MainWindow.setStyleSheet("background:black;\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file = QtWidgets.QPushButton(self.centralwidget)
        self.file.setGeometry(QtCore.QRect(20, 10, 261, 51))
        self.file.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}\n"
"")
        self.file.setObjectName("file")
        self.listpictures = QtWidgets.QListWidget(self.centralwidget)
        self.listpictures.setGeometry(QtCore.QRect(20, 90, 261, 601))
        self.listpictures.setStyleSheet("border:3px solid #ffffff;\n"
"border-radius: 12px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.listpictures.setObjectName("listpictures")
        self.pictures = QtWidgets.QLabel(self.centralwidget)
        self.pictures.setGeometry(QtCore.QRect(300, 20, 681, 611))
        self.pictures.setStyleSheet("border:3px dotted #ffffff;\n"
"border-radius: 12px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.pictures.setObjectName("pictures")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(300, 640, 131, 51))
        self.left.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}\n"
"")
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(440, 640, 131, 51))
        self.right.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}\n"
"")
        self.right.setObjectName("right")
        self.mirror = QtWidgets.QPushButton(self.centralwidget)
        self.mirror.setGeometry(QtCore.QRect(580, 640, 131, 51))
        self.mirror.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}\n"
"")
        self.mirror.setObjectName("mirror")
        self.sharpness = QtWidgets.QPushButton(self.centralwidget)
        self.sharpness.setGeometry(QtCore.QRect(720, 640, 131, 51))
        self.sharpness.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}")
        self.sharpness.setObjectName("sharpness")
        self.b_w = QtWidgets.QPushButton(self.centralwidget)
        self.b_w.setGeometry(QtCore.QRect(860, 640, 131, 51))
        self.b_w.setStyleSheet("QPushButton {\n"
"    border:3px dashed #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size:20px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#2C2D2C;\n"
"}")
        self.b_w.setObjectName("b_w")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photopop"))
        self.file.setText(_translate("MainWindow", "File"))
        self.pictures.setText(_translate("MainWindow", "Picture"))
        self.left.setText(_translate("MainWindow", "Left"))
        self.right.setText(_translate("MainWindow", "Right"))
        self.mirror.setText(_translate("MainWindow", "Mirror"))
        self.sharpness.setText(_translate("MainWindow", "Blur"))
        self.b_w.setText(_translate("MainWindow", "Black/White"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
